title: Rajita Chandak
author: Rajita Chandak
email: rchandak@princeton.edu
url: 'https:/rajitachandak.github.io'

# Build Settings
theme: minima

# Exclude from build
exclude:
 - Gemfile
 - Gemfile.lock

#theme settings
minima:
  date_format: "%b %-d, %Y"


header_pages:
 - publications.md
 - software.md
 - contact.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag

