---
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: assets/docs/Chandak_CV.tex
      - name: Push generated files to branch 'gh-pages'
        run: |
          mv *.pdf assets/docs/*.pdf
          git add assets/docs/*.pdf
          git commit -m "Build CV"
          git push 
        if: ${{ success() }}
